-- =============================================================================
-- best_city_finds: keresési találatok — all_parameters pillanatkép + match_score
-- =============================================================================
--
-- Előfeltétel: public.all_parameters létezik és feltöltve.
--
-- Meta oszlopok (csak ezek + all_parameters):
--   id, created_at, match_score  (egyezés %, 0–100)
--
-- Nincs külön: telepules_nev, lat, lng, erdo_ertek, kultura_ertek, egyezes_pontszam
--   → settlement_name, CITYDATA_Latitude / CITYDATA_Longitude, index oszlopok az all_parameters-ben.
--
-- Ha korábban futott a talalatok_schema.sql: a régi táblát átnevezi *_legacy névre.
-- Oszlop-szinkron: a 3. szakasz futtatható többször (új all_parameters oszlopokhoz).
-- =============================================================================

-- ── 1. Régi táblák mentése ───────────────────────────────────────────────────

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'talalatok'
  )
  AND NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'best_city_finds'
  ) THEN
    ALTER TABLE public.talalatok RENAME TO talalatok_legacy;
    RAISE NOTICE 'talalatok → talalatok_legacy';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'best_city_finds'
  )
  AND EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'best_city_finds'
      AND column_name = 'telepules_nev'
  )
  AND NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'best_city_finds_legacy'
  ) THEN
    ALTER TABLE public.best_city_finds RENAME TO best_city_finds_legacy;
    RAISE NOTICE 'Régi best_city_finds (telepules_nev stb.) → best_city_finds_legacy';
  END IF;
END $$;

-- ── 2. Új best_city_finds váz ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.best_city_finds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  match_score double precision
);

COMMENT ON TABLE public.best_city_finds IS
  '„Tökéletes hely” keresés eredménye: all_parameters sor + egyezés százalék (match_score).';
COMMENT ON COLUMN public.best_city_finds.id IS 'Sorszám / jegy (projector, realtime INSERT).';
COMMENT ON COLUMN public.best_city_finds.created_at IS 'Keresés időpontja.';
COMMENT ON COLUMN public.best_city_finds.match_score IS 'Egyezés százalék (0–100); 100 = tökéletes egyezés.';

-- Régi meta oszlopok eltávolítása, ha egy korábbi séma már létrejött
ALTER TABLE public.best_city_finds DROP COLUMN IF EXISTS telepules_nev;
ALTER TABLE public.best_city_finds DROP COLUMN IF EXISTS lat;
ALTER TABLE public.best_city_finds DROP COLUMN IF EXISTS lng;
ALTER TABLE public.best_city_finds DROP COLUMN IF EXISTS erdo_ertek;
ALTER TABLE public.best_city_finds DROP COLUMN IF EXISTS kultura_ertek;
ALTER TABLE public.best_city_finds DROP COLUMN IF EXISTS egyezes_pontszam;

-- ── 3. Oszlopok szinkronizálása all_parameters-ből ──────────────────────────

DO $$
DECLARE
  r RECORD;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'all_parameters'
  ) THEN
    RAISE EXCEPTION 'Előbb hozd létre és töltsd fel a public.all_parameters táblát.';
  END IF;

  FOR r IN
    SELECT
      a.attname AS col_name,
      pg_catalog.format_type(a.atttypid, a.atttypmod) AS col_type
    FROM pg_catalog.pg_attribute a
    JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'all_parameters'
      AND a.attnum > 0
      AND NOT a.attisdropped
      AND a.attname NOT IN ('created_at')
    ORDER BY a.attnum
  LOOP
    EXECUTE format(
      'ALTER TABLE public.best_city_finds ADD COLUMN IF NOT EXISTS %I %s',
      r.col_name,
      r.col_type
    );
  END LOOP;

  RAISE NOTICE 'all_parameters oszlopok → best_city_finds.';
END $$;

-- ── 4. Indexek ───────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS best_city_finds_created_at_idx
  ON public.best_city_finds (created_at DESC);

CREATE INDEX IF NOT EXISTS best_city_finds_settlement_name_idx
  ON public.best_city_finds (settlement_name);

CREATE INDEX IF NOT EXISTS best_city_finds_parameter_id_idx
  ON public.best_city_finds ("ID");

CREATE INDEX IF NOT EXISTS best_city_finds_match_score_idx
  ON public.best_city_finds (match_score DESC);

-- ── 5. Legacy átvitel (meta + all_parameters join, ahol lehet) ───────────────

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'talalatok_legacy'
  ) THEN
    INSERT INTO public.best_city_finds (
      id,
      created_at,
      match_score,
      settlement_name,
      "CITYDATA_Latitude",
      "CITYDATA_Longitude"
    )
    SELECT
      l.id,
      COALESCE(l.created_at, now()),
      COALESCE(l.match_score, l.egyezes_pontszam),
      COALESCE(l.settlement_name, l.telepules_nev),
      COALESCE(l."CITYDATA_Latitude", l.lat),
      COALESCE(l."CITYDATA_Longitude", l.lng)
    FROM public.talalatok_legacy l
    WHERE NOT EXISTS (SELECT 1 FROM public.best_city_finds b WHERE b.id = l.id);

    PERFORM setval(
      pg_get_serial_sequence('public.best_city_finds', 'id'),
      COALESCE((SELECT MAX(id) FROM public.best_city_finds), 1)
    );
    RAISE NOTICE 'talalatok_legacy → best_city_finds (részleges meta).';
  END IF;
EXCEPTION
  WHEN undefined_column OR undefined_table THEN
    RAISE NOTICE 'talalatok_legacy átvitel kihagyva (oszlop/tábla eltérés).';
END $$;

-- ── 6. Realtime + RLS ───────────────────────────────────────────────────────

ALTER TABLE public.best_city_finds REPLICA IDENTITY FULL;

ALTER TABLE public.best_city_finds ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "best_city_finds_select_anon" ON public.best_city_finds;
CREATE POLICY "best_city_finds_select_anon"
  ON public.best_city_finds
  FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "best_city_finds_insert_anon" ON public.best_city_finds;
CREATE POLICY "best_city_finds_insert_anon"
  ON public.best_city_finds
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- Supabase Dashboard → Database → Publications: best_city_finds engedélyezése realtime-hoz.
--
-- Ha az INSERT mégsem látszik a Table Editorben: Authentication → Policies,
-- vagy futtasd újra a 7. szakaszt. A REST API-n az anon kulcsnak kell INSERT + SELECT.

-- =============================================================================
-- Ellenőrzés:
-- SELECT id, created_at, match_score, settlement_name FROM public.best_city_finds
-- ORDER BY id DESC LIMIT 5;
-- =============================================================================
